// DMP9_ExportC.java — Ghidra 11.x / 12.x
//
// Exports decompiled C output for all named (non-FUN_) functions to a
// directory tree under OUT_DIR.  Designed for the DMP9/16 round-trip
// workflow:
//
//   1. Ghidra analysis / naming (GUI or headless scripts)
//   2. DMP9_ExportC dumps named functions to .c + combined header
//   3. compile.sh attempts m68k-gcc on the result
//   4. compare_roms.py diffs output .bin against original ROM
//
// OUTPUT STRUCTURE
// ────────────────
//   $OUT_DIR/<romname>/
//       all_functions.c       — single concatenated decompile for grepping
//       all_functions.h       — forward declarations + struct typedefs
//       functions/<name>.c    — one file per named function
//       index.tsv             — address, name, CC, size, decompile_ok
//
// CONFIGURATION
// ─────────────
// Set OUT_DIR via script argument or env var DMP9_EXPORT_DIR.
// Default: ~/dmp9_export/<programname>/
//
// USAGE (headless)
// ────────────────
//   analyzeHeadless ~/ghidra_projects DMP9-16 \
//     -process "TMS27C240-10-DMP9-16-XN349G0-v1.11-10.03.1994.bin" \
//     -noanalysis \
//     -postScript DMP9_ExportC.java \
//     -scriptPath ~/devel/DMP9-16/ghidra/scripts
//
// Or via run_analysis.sh --export
//
// @author  DMP9-16 project
// @category DMP9
// @keybinding
// @menupath
// @toolbar

import ghidra.app.decompiler.*;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.listing.Function.FunctionUpdateType;
import ghidra.program.model.symbol.*;
import ghidra.util.task.ConsoleTaskMonitor;

import java.io.*;
import java.nio.file.*;
import java.util.*;

public class DMP9_ExportC extends GhidraScript {

    // -----------------------------------------------------------------------
    // Configuration
    // -----------------------------------------------------------------------

    /** Functions starting with these prefixes are skipped (auto-generated names). */
    private static final String[] SKIP_PREFIXES = {
        "FUN_", "DAT_", "LAB_", "SUB_", "thunk_FUN_"
    };

    /** Decompiler timeout per function in seconds. */
    private static final int DECOMPILE_TIMEOUT_S = 60;

    // -----------------------------------------------------------------------
    // Entry point
    // -----------------------------------------------------------------------

    @Override
    public void run() throws Exception {
        String progName = currentProgram.getName();

        // Resolve output directory: arg[0] > env > default
        String outDirStr;
        String[] args = getScriptArgs();
        if (args != null && args.length > 0 && !args[0].isBlank()) {
            outDirStr = args[0];
        } else {
            String envDir = System.getenv("DMP9_EXPORT_DIR");
            if (envDir != null && !envDir.isBlank()) {
                outDirStr = envDir + "/" + sanitize(progName);
            } else {
                outDirStr = System.getProperty("user.home") + "/dmp9_export/" + sanitize(progName);
            }
        }

        Path outDir = Paths.get(outDirStr);
        Path funcDir = outDir.resolve("functions");
        Files.createDirectories(funcDir);

        println("[DMP9_ExportC] Output: " + outDir);

        // -----------------------------------------------------------------------
        // Set up decompiler
        // -----------------------------------------------------------------------
        DecompInterface decompiler = new DecompInterface();
        DecompileOptions options = new DecompileOptions();
        options.setMaxInstructions(100000);
        decompiler.setOptions(options);
        decompiler.setSimplificationStyle("decompile");
        if (!decompiler.openProgram(currentProgram)) {
            printerr("[DMP9_ExportC] Failed to open decompiler: " + decompiler.getLastMessage());
            return;
        }

        // -----------------------------------------------------------------------
        // Iterate functions
        // -----------------------------------------------------------------------
        FunctionIterator funcIter = currentProgram.getFunctionManager().getFunctions(true);

        List<String> allC = new ArrayList<>();
        List<String> headerLines = new ArrayList<>();
        List<String[]> index = new ArrayList<>();

        int exported = 0, skipped = 0, failed = 0;

        allC.add("/* DMP9/16 decompiled output — " + progName + " */");
        allC.add("/* Generated by DMP9_ExportC.java (Ghidra) */");
        allC.add("#include \"all_functions.h\"");
        allC.add("");

        headerLines.add("/* DMP9/16 function declarations — " + progName + " */");
        headerLines.add("#pragma once");
        headerLines.add("#include <stdint.h>");
        headerLines.add("");
        headerLines.add("/* Board I/O addresses */");
        headerLines.add("#define LCD_CMD   (*(volatile uint8_t *)0x490000UL)");
        headerLines.add("#define LCD_DATA  (*(volatile uint8_t *)0x490001UL)");
        headerLines.add("#define DSP_EF1   (*(volatile uint8_t *)0x460000UL)");
        headerLines.add("#define DSP_EF2   (*(volatile uint8_t *)0x470000UL)");
        headerLines.add("");

        index.add(new String[]{"address", "name", "calling_convention", "size_bytes", "decompile_ok"});

        monitor.setMessage("Exporting decompiled C...");
        monitor.setMaximum(currentProgram.getFunctionManager().getFunctionCount());
        int monCount = 0;

        while (funcIter.hasNext()) {
            if (monitor.isCancelled()) break;
            monitor.setProgress(monCount++);

            Function func = funcIter.next();
            String name = func.getName();

            // Skip auto-named functions
            if (shouldSkip(name)) {
                skipped++;
                continue;
            }

            Address entry = func.getEntryPoint();
            String cc = func.getCallingConventionName();
            long sizeBytes = func.getBody().getNumAddresses();
            String addrHex = "0x" + entry.toString().toUpperCase();

            // Decompile
            DecompileResults res = decompiler.decompileFunction(func, DECOMPILE_TIMEOUT_S, monitor);
            boolean ok = res != null && res.decompileCompleted();
            String cText;

            if (ok) {
                cText = res.getDecompiledFunction().getC();
                exported++;
            } else {
                String reason = (res != null) ? res.getErrorMessage() : "timeout/null";
                cText = "/* DECOMPILE FAILED: " + name + " @ " + addrHex + " — " + reason + " */\n";
                failed++;
            }

            // Write per-function file
            String fname = sanitize(name) + ".c";
            Path funcFile = funcDir.resolve(fname);
            try (PrintWriter w = new PrintWriter(new FileWriter(funcFile.toFile()))) {
                w.println("/* " + name + " @ " + addrHex
                        + "  cc=" + cc + "  size=" + sizeBytes + " bytes */");
                w.println("#include \"../all_functions.h\"");
                w.println();
                w.print(cText);
            }

            // Append to combined .c
            allC.add("/* ── " + name + " @ " + addrHex + " ── */");
            allC.add(cText);

            // Add forward declaration to header
            if (ok) {
                // Extract prototype line (first non-blank, non-comment line)
                String proto = extractPrototype(cText, name);
                if (proto != null) {
                    headerLines.add(proto + ";  /* @ " + addrHex + " */");
                }
            }

            index.add(new String[]{addrHex, name, cc, String.valueOf(sizeBytes), ok ? "yes" : "NO"});
        }

        decompiler.dispose();

        // -----------------------------------------------------------------------
        // Write combined files
        // -----------------------------------------------------------------------
        writeLines(outDir.resolve("all_functions.c"), allC);
        writeLines(outDir.resolve("all_functions.h"), headerLines);

        // Write index.tsv
        try (PrintWriter w = new PrintWriter(new FileWriter(outDir.resolve("index.tsv").toFile()))) {
            for (String[] row : index) {
                w.println(String.join("\t", row));
            }
        }

        // -----------------------------------------------------------------------
        // Summary
        // -----------------------------------------------------------------------
        println("[DMP9_ExportC] Done.");
        println("  Exported : " + exported);
        println("  Skipped  : " + skipped + "  (auto-named FUN_/DAT_/etc.)");
        println("  Failed   : " + failed);
        println("  Output   : " + outDir);
        println("");
        println("Next: cd " + outDir + " && bash ../../compile.sh");
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private boolean shouldSkip(String name) {
        for (String pfx : SKIP_PREFIXES) {
            if (name.startsWith(pfx)) return true;
        }
        return false;
    }

    /** Sanitize a function name to a safe filename. */
    private String sanitize(String name) {
        return name.replaceAll("[^A-Za-z0-9_\\-.]", "_");
    }

    /**
     * Extract the function prototype from decompiled C text.
     * Returns the first line that looks like a return-type + function name,
     * or null if not found.
     */
    private String extractPrototype(String cText, String funcName) {
        for (String line : cText.split("\n")) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("/*") || trimmed.startsWith("//")) continue;
            // A prototype line typically contains the function name and a '('
            if (trimmed.contains(funcName) && trimmed.contains("(")) {
                // Strip trailing '{' if present
                String proto = trimmed.replaceAll("\\s*\\{\\s*$", "").trim();
                return proto;
            }
        }
        return null;
    }

    private void writeLines(Path path, List<String> lines) throws IOException {
        try (PrintWriter w = new PrintWriter(new FileWriter(path.toFile()))) {
            for (String line : lines) {
                w.println(line);
            }
        }
    }
}
