/**
 * @file dmp9_board_regs.h
 * @brief Yamaha DMP9 / DMP16 Board-Specific Peripheral Definitions
 *
 * This header is a companion to tmp68301_regs.h and provides address
 * definitions, constants, and bitfield descriptions for the external
 * peripherals found on the Yamaha DMP9 and DMP16 digital rack mixer
 * boards.
 *
 * ===========================================================================
 * BOARD ARCHITECTURE SUMMARY (from Yamaha DMP9/DMP16 service manual diagrams)
 * ===========================================================================
 *
 * CPU Section (DIG board, IC24):
 *   IC24   = TMP68301A @ 16 MHz  — main CPU
 *   IC34   = ROM                 — firmware (single ROM chip)
 *   IC93/94= SRAM                — CPU working SRAM (address TBD from firmware)
 *
 * DSP Section (shaded "DSP SECTION" block in block diagrams):
 *   DEQ2 units: IC26,27,28,37,38,39  (6 units, labelled DEQ2-1..6, one per
 *               stereo input pair; "DEQ2" = waveform format name per diagram
 *               legend; likely implemented by YM3807)
 *   DSP2 units: IC19,29,46,56,70,71  (5 units, labelled DSP2-1..5 + master;
 *               handle Mix/Level/On-Off per group; likely YM3804)
 *   MEG unit:   IC22,23              (metering engine; AUXMEL0/1, IMEL0-3,
 *               OMEL0/1 signals; likely YM6104 or YM6007)
 *   SRAM:       IC66,67,68           (DSP coefficient/program SRAM in DSP block)
 *   DRAM:       IC35,36              (64 KB delay/effects DRAM used by DSP2
 *                                    units 3/4/5 — see note below)
 *
 * IMPORTANT: The DRAM at 0x400000 is DUAL-PURPOSE (CPU + DSP shared).
 *   The reset vector places the TMP68301 stack pointer just above 0x400000
 *   (confirmed from ROM), proving the CPU has full read/write access to this
 *   region.  The DSP2 section also uses the same physical ICs (IC35/36) for
 *   delay-based effects via a time-division shared bus — a standard arrangement
 *   in late-80s/early-90s Yamaha DSP hardware.
 *   Probable layout within 0x400000–0x40FFFF:
 *     Low addresses  : DSP delay/effects buffer (written by DSP2 units 3/4/5)
 *     High addresses : CPU stack and working variables (SP init near 0x40FFFF)
 *   The exact boundary between DSP and CPU usage must be confirmed from
 *   firmware analysis (watch for the SP initialisation and first MOVE.L
 *   writes into the region).
 *
 *   The IC93/94 SRAM visible in the CPU section block is likely a separate,
 *   smaller static RAM used for a different purpose (e.g. patch/preset storage
 *   or display buffer) at an as-yet-unknown address — or it may be the same
 *   physical chips as IC35/36 seen from the CPU bus side (board-dependent).
 *
 * Clock / PLL Section:
 *   IC45/IC49/IC96 + XTAL  — PLL generating 512FS @ 48 kHz
 *   XTAL frequency = 512 × 48000 = 24.576 MHz
 *   IC50 + IC30,31,51,57   — DIV & PLD: clock division and address decode logic
 *   Outputs: 256(M), 128(M), 64(M), FS(M), SYNC to DSP section
 *            256(D1/D2), 64(D1/D2), FS(D1/D2) to digital input receivers
 *
 * Address Decoding:
 *   Performed entirely by IC50 (PLD) and supporting divider ICs.
 *   The TMP68301 CS0/CS1 chip-select outputs and AMAR0/AAMR0/AMAR1/AAMR1
 *   registers do NOT govern the LCD or DSP address windows.
 *   CS CONTROL signals (LOCK(D1), LOCK(D2), LOCK(M)) are generated by the
 *   PLD based on clock-lock status of the digital input receivers.
 *
 * Digital I/O:
 *   IC58,101 = DIR2  — two digital input receivers (AES/EBU or S/PDIF)
 *   IC43,100 = DIT2  — two digital output transmitters
 *   IC73,65,59       — WAVE REFORM for digital input 1
 *
 * Signal format legend (from diagram footnote):
 *   Labels in <> (e.g. <ST-DSP>, <DSP2>) = waveform/data format names
 *   Labels without <> (e.g. DEQ2, DSP2, MEG) = functional block names
 *   Both are used on the SIO bus signals connecting DSP ICs.
 *
 * Analog path (ANAU/ANAL/ANA boards):
 *   Per-input chain: Op-Amp → FPB → Pre-Emp → DC OFFSET → A/D Converter
 *   Output chain:    D/A → Op-Amp → De-Emp → FPR → balanced/unbalanced out
 *   CLK(FOR MASTER) and CLK(FOR MON) are separate clock domains.
 *
 * LCD physical interface:
 *   PWR board CN5 (PH-2P TE) carries LCD backlight power (separate from data).
 *   Data interface (LCD_CMD/LCD_DATA) is on the DIG board, routed via CPU.
 *
 * ===========================================================================
 * CONFIRMED MEMORY MAP (DMP9/DMP16)
 * ===========================================================================
 *   0x000000           ROM           (IC34 — single firmware ROM)
 *   0x400000           SHARED_DRAM   (IC35,36 — 64 KB, dual-purpose)
 *                                   CPU: stack + working RAM  (SP init just above 0x400000,
 *                                        confirmed from ROM reset vector)
 *                                   DSP: delay/effects buffer (DSP2 units 3/4/5)
 *   0x460000           DSP_EF1_BASE  (YM3804 + YM6007 + YM3807 + YM6104)
 *   0x470000           DSP_EF2_BASE  (YM3804 + YM3807)
 *   0x490000           LCD_CMD       (HD44780, RS=0 — command register)
 *   0x490001           LCD_DATA      (HD44780, RS=1 — data register)
 *   ???                CPU_SRAM      (IC93,IC94 — address TBD)
 *   0xFFFC00           TMP68301 internal peripheral registers
 *
 * Sources:
 *   - Yamaha DMP9/DMP16 service manual hardware block diagrams (N8-B7)
 *   - Yamaha DMP9/DMP16 hardware analysis (firmware disassembly)
 *   - HD44780U datasheet, Hitachi Semiconductor, rev. 0.0
 *   - Yamaha DSP chip list (dtech.lv/techarticles_yamaha_chips.html)
 */

#ifndef DMP9_BOARD_REGS_H
#define DMP9_BOARD_REGS_H

#include <stdint.h>
#include "tmp68301_regs.h"

#ifdef __cplusplus
extern "C" {
#endif


/* =========================================================================
 * SECTION 1 – HD44780 LCD CONTROLLER
 *
 * The HD44780 is interfaced via two adjacent byte addresses.  The RS
 * (register-select) line distinguishes commands from data; on the DMP9
 * this is wired so that:
 *   0x490000  RS=0  → Instruction Register (write command / read busy flag)
 *   0x490001  RS=1  → Data Register        (write/read DDRAM or CGRAM)
 *
 * The DMP9/DMP16 display is a 4-line × 20-character LCD module.
 * HD44780 DDRAM layout for common 4-line, 20-char displays:
 *   Line 1: 0x00–0x13   (display column 0–19)
 *   Line 2: 0x40–0x53
 *   Line 3: 0x14–0x27   ← some 4-line modules use 0x14 offset for line 3
 *   Line 4: 0x54–0x67
 *
 * Verify the exact line-3/4 base by watching the firmware's Set-DDRAM
 * commands (opcodes 0x80–0xFF) during initialisation.
 * ========================================================================= */

/** LCD command register (RS=0): write instruction, read busy flag + AC */
#define LCD_CMD                 0x490000UL

/** LCD data register (RS=1): write/read DDRAM or CGRAM data */
#define LCD_DATA                0x490001UL


/* -------------------------------------------------------------------------
 * HD44780 Instruction Set
 * All values are written to LCD_CMD (RS=0).
 * Execution times assume fosc ~270 kHz (typical 5V HD44780).
 * -------------------------------------------------------------------------- */

/* --- Housekeeping commands ------------------------------------------------ */
#define LCD_CMD_CLEAR_DISPLAY   0x01  /**< Clear all DDRAM, reset AC to 0.   ~1.52 ms */
#define LCD_CMD_RETURN_HOME     0x02  /**< Reset AC to 0, return shifted display. ~1.52 ms */

/* --- Entry Mode Set (0x04–0x07): set cursor move direction + display shift -- */
/** @defgroup LCD_ENTRY Entry Mode Set (0x04 base) */
#define LCD_CMD_ENTRY_MODE_BASE 0x04  /**< Base opcode; OR the flags below */
#define LCD_ENTRY_INC           0x02  /**< Increment AC after each R/W (cursor right) */
#define LCD_ENTRY_DEC           0x00  /**< Decrement AC after each R/W (cursor left) */
#define LCD_ENTRY_SHIFT         0x01  /**< Shift display on write (INC→left; DEC→right) */
#define LCD_ENTRY_NOSHIFT       0x00  /**< No display shift */

/* Commonly used composite values */
#define LCD_CMD_ENTRY_INC_NOSHIFT   0x06  /**< Increment, no shift  (typical init) */
#define LCD_CMD_ENTRY_DEC_NOSHIFT   0x04  /**< Decrement, no shift */
#define LCD_CMD_ENTRY_INC_SHIFT     0x07  /**< Increment + shift display left */
#define LCD_CMD_ENTRY_DEC_SHIFT     0x05  /**< Decrement + shift display right */

/* --- Display ON/OFF Control (0x08–0x0F) ------------------------------------- */
/** @defgroup LCD_DISP Display ON/OFF Control (0x08 base) */
#define LCD_CMD_DISPLAY_BASE    0x08  /**< Base opcode; OR the flags below */
#define LCD_DISP_ON             0x04  /**< Display ON */
#define LCD_DISP_OFF            0x00  /**< Display OFF (contents preserved in DDRAM) */
#define LCD_CURSOR_ON           0x02  /**< Underline cursor visible */
#define LCD_CURSOR_OFF          0x00  /**< Cursor off */
#define LCD_BLINK_ON            0x01  /**< Blinking block cursor */
#define LCD_BLINK_OFF           0x00  /**< No blink */

/* Commonly used composite values */
#define LCD_CMD_DISPLAY_OFF         0x08  /**< Display off, cursor off, blink off */
#define LCD_CMD_DISPLAY_ON_NOCURSOR 0x0C  /**< Display on, cursor off */
#define LCD_CMD_DISPLAY_ON_CURSOR   0x0E  /**< Display on, cursor on (underline) */
#define LCD_CMD_DISPLAY_ON_BLINK    0x0F  /**< Display on, cursor on + blinking block */

/* --- Cursor / Display Shift (0x10–0x1F) ------------------------------------- */
/** @defgroup LCD_SHIFT Cursor / Display Shift (0x10 base) */
#define LCD_CMD_SHIFT_BASE      0x10  /**< Base opcode; OR the flags below */
#define LCD_SHIFT_DISPLAY       0x08  /**< 1=shift display, 0=move cursor */
#define LCD_SHIFT_CURSOR        0x00
#define LCD_SHIFT_RIGHT         0x04  /**< Shift/move right */
#define LCD_SHIFT_LEFT          0x00  /**< Shift/move left */

/* Commonly used composite values */
#define LCD_CMD_CURSOR_LEFT         0x10  /**< Move cursor one position left */
#define LCD_CMD_CURSOR_RIGHT        0x14  /**< Move cursor one position right */
#define LCD_CMD_DISPLAY_LEFT        0x18  /**< Shift entire display one position left */
#define LCD_CMD_DISPLAY_RIGHT       0x1C  /**< Shift entire display one position right */

/* --- Function Set (0x20–0x3F) ----------------------------------------------- */
/** @defgroup LCD_FUNC Function Set (0x20 base) */
#define LCD_CMD_FUNCTION_BASE   0x20  /**< Base opcode; OR the flags below */
#define LCD_FUNC_8BIT           0x10  /**< 8-bit data bus (DL=1) */
#define LCD_FUNC_4BIT           0x00  /**< 4-bit data bus (DL=0) */
#define LCD_FUNC_2LINE          0x08  /**< 2-line (or 4-line) display (N=1) */
#define LCD_FUNC_1LINE          0x00  /**< 1-line display (N=0) */
#define LCD_FUNC_FONT5x10       0x04  /**< 5×10 dot font (F=1, 1-line mode only) */
#define LCD_FUNC_FONT5x8        0x00  /**< 5×8 dot font  (F=0) */

/* Commonly used composite values */
#define LCD_CMD_FUNC_8BIT_1LINE_5x8  0x30  /**< 8-bit bus, 1-line, 5×8 font */
#define LCD_CMD_FUNC_8BIT_2LINE_5x8  0x38  /**< 8-bit bus, 2/4-line, 5×8 font (standard init) */
#define LCD_CMD_FUNC_4BIT_1LINE_5x8  0x20  /**< 4-bit bus, 1-line, 5×8 font */
#define LCD_CMD_FUNC_4BIT_2LINE_5x8  0x28  /**< 4-bit bus, 2/4-line, 5×8 font */

/* --- Set CGRAM Address (0x40–0x7F) ------------------------------------------ */
/**
 * Set CGRAM address counter.  After this command, subsequent LCD_DATA
 * writes store character generator pattern bytes at successive CGRAM
 * addresses.  The HD44780 supports 8 user-defined 5×8 characters (slots 0–7).
 *
 *   opcode = LCD_CMD_SET_CGRAM_ADDR | (char_index << 3) | row_index
 *   char_index: 0–7 (which of the 8 custom characters)
 *   row_index:  0–7 (which of the 8 pixel rows of that character)
 *
 *   Full CGRAM address = (char_index * 8) + row_index
 */
#define LCD_CMD_SET_CGRAM_BASE  0x40  /**< Base opcode; OR 6-bit CGRAM address */
#define LCD_CGRAM_ADDR(n)       (LCD_CMD_SET_CGRAM_BASE | ((n) & 0x3F))
#define LCD_CGRAM_CHAR(ch, row) LCD_CGRAM_ADDR(((ch) & 0x07) << 3 | ((row) & 0x07))

/* --- Set DDRAM Address (0x80–0xFF) ------------------------------------------ */
/**
 * Set DDRAM address counter.  After this command, subsequent LCD_DATA
 * writes go to the display at the addressed position.
 *
 * DMP9 / DMP16 display — 4-line × 20-char, using standard HD44780 mapping:
 *
 *   Line 1:  DDRAM 0x00–0x13   opcode 0x80–0x93
 *   Line 2:  DDRAM 0x40–0x53   opcode 0xC0–0xD3
 *   Line 3:  DDRAM 0x14–0x27   opcode 0x94–0xA7  (verify from firmware trace)
 *   Line 4:  DDRAM 0x54–0x67   opcode 0xD4–0xE7  (verify from firmware trace)
 *
 * The line 3/4 base offsets (0x14/0x54) are the most common variant for
 * 4-line 20-char displays but some modules use 0x10/0x50 or 0x00/0x40
 * for lines 3/4.  Cross-check against the firmware initialisation sequence.
 */
#define LCD_CMD_SET_DDRAM_BASE  0x80  /**< Base opcode; OR 7-bit DDRAM address */
#define LCD_DDRAM_ADDR(n)       (LCD_CMD_SET_DDRAM_BASE | ((n) & 0x7F))

/* DDRAM line base addresses (standard 4×20 mapping) */
#define LCD_DDRAM_LINE1         0x00  /**< DDRAM address for start of line 1 */
#define LCD_DDRAM_LINE2         0x40  /**< DDRAM address for start of line 2 */
#define LCD_DDRAM_LINE3         0x14  /**< DDRAM address for start of line 3 (verify) */
#define LCD_DDRAM_LINE4         0x54  /**< DDRAM address for start of line 4 (verify) */
#define LCD_DDRAM_LINE_LEN      20    /**< Characters per display line */

/* Convenience: opcode to jump to start of a numbered line (1-based) */
#define LCD_CMD_HOME_LINE1      LCD_DDRAM_ADDR(LCD_DDRAM_LINE1)  /* 0x80 */
#define LCD_CMD_HOME_LINE2      LCD_DDRAM_ADDR(LCD_DDRAM_LINE2)  /* 0xC0 */
#define LCD_CMD_HOME_LINE3      LCD_DDRAM_ADDR(LCD_DDRAM_LINE3)  /* 0x94 */
#define LCD_CMD_HOME_LINE4      LCD_DDRAM_ADDR(LCD_DDRAM_LINE4)  /* 0xD4 */

/* --- Busy Flag / Address Counter read (LCD_CMD read) ------------------------- */
/**
 * Reading LCD_CMD (RS=0) returns:
 *   Bit [7]: BF – Busy Flag (1=busy executing previous command)
 *   Bits[6:0]: AC – current Address Counter value (DDRAM or CGRAM)
 * Poll BF before each command write.  The DMP9 firmware may use fixed
 * delays instead of polling BF — check the firmware's read-back loop.
 */
#define LCD_BF                  0x80  /**< Busy Flag mask in command read */
#define LCD_AC_MASK             0x7F  /**< Address Counter mask in command read */


/* -------------------------------------------------------------------------
 * HD44780 Command → Semantic Decode Table
 *
 * Used by DMP9_Board_Setup.java to add descriptive pre-comments at every
 * store instruction that writes a constant byte to LCD_CMD.
 *
 * The decode logic in the Ghidra script applies the following rules in
 * order (most specific mask checked first):
 *
 *   Value range 0x80–0xFF  →  "Set DDRAM addr=0x%02X  [line %d, col %d]"
 *   Value range 0x40–0x7F  →  "Set CGRAM addr=0x%02X  [char %d, row %d]"
 *   Value        0x38       →  "Function Set: 8-bit, 2-line, 5×8  (standard init)"
 *   Value        0x30       →  "Function Set: 8-bit, 1-line, 5×8"
 *   Value        0x28       →  "Function Set: 4-bit, 2-line, 5×8"
 *   Value        0x20       →  "Function Set: 4-bit, 1-line, 5×8"
 *   Value        0x1C       →  "Shift Display Right"
 *   Value        0x18       →  "Shift Display Left"
 *   Value        0x14       →  "Shift Cursor Right"
 *   Value        0x10       →  "Shift Cursor Left"
 *   Value        0x0F       →  "Display ON + Cursor ON + Blink"
 *   Value        0x0E       →  "Display ON + Cursor ON"
 *   Value        0x0C       →  "Display ON, Cursor OFF"
 *   Value        0x08       →  "Display OFF"
 *   Value        0x07       →  "Entry Mode: Increment + Display Shift"
 *   Value        0x06       →  "Entry Mode: Increment, no shift"
 *   Value        0x05       →  "Entry Mode: Decrement + Display Shift"
 *   Value        0x04       →  "Entry Mode: Decrement, no shift"
 *   Value        0x03       →  "Return Home  (wait ≥1.52 ms)"
 *   Value        0x02       →  "Return Home  (wait ≥1.52 ms)"
 *   Value        0x01       →  "Clear Display  (wait ≥1.52 ms)"
 *   Value        0x00       →  "NOP / no-op write"
 * -------------------------------------------------------------------------- */


/* =========================================================================
 * SECTION 2 – YM-series DSP CHIPS
 *
 * The DMP9/DMP16 contains two independent DSP effect blocks, each
 * addressed via a dedicated base address.  Both blocks are accessed
 * using byte writes from the TMP68301; address decoding is external.
 *
 * EF1 block (effects 1):  YM3804 + YM6007 + YM3807 + YM6104
 * EF2 block (effects 2):  YM3804 + YM3807
 *
 * WARNING: Yamaha YM3804, YM3807, YM6007, and YM6104 are proprietary
 * DSP chips with no publicly available register documentation.  All
 * register/port offsets below are derived from firmware disassembly and
 * should be treated as tentative until verified.
 *
 * Ghidra annotation strategy (see DMP9_Board_Setup.java):
 *   - Label each DSP base as DSP_EF1_BASE / DSP_EF2_BASE
 *   - Mark the entire 64-KB window as an overlay block
 *   - Add a plate comment listing chip composition
 *   - As register offsets are discovered via firmware analysis,
 *     they can be added as further defineReg() calls below the base
 * ========================================================================= */

/* DSP block base addresses */
#define DSP_EF1_BASE            0x460000UL  /**< EF1: YM3804 + YM6007 + YM3807 + YM6104 */
#define DSP_EF2_BASE            0x470000UL  /**< EF2: YM3804 + YM3807 */

/* DSP block window size (address space reserved per block) */
#define DSP_BLOCK_SIZE          0x010000UL  /**< 64 KB address window per DSP block */

/** Convenience macro: absolute address within a DSP block */
#define DSP_EF1_REG(off)        (DSP_EF1_BASE + (off))
#define DSP_EF2_REG(off)        (DSP_EF2_BASE + (off))


/* -------------------------------------------------------------------------
 * YM3804 – DSP Core (present in EF1 and EF2)
 *
 * The YM3804 appears to be a programmable DSP core.  The firmware
 * loads coefficient/program data into it during initialisation.
 * No public register map exists.  Placeholder offsets below are derived
 * from observed firmware access patterns and are UNVERIFIED.
 * -------------------------------------------------------------------------- */
#define YM3804_EF1_BASE         DSP_EF1_REG(0x0000)  /**< YM3804 in EF1 block — unverified offset */
#define YM3804_EF2_BASE         DSP_EF2_REG(0x0000)  /**< YM3804 in EF2 block — unverified offset */

/* YM3804 candidate register offsets (firmware-derived, UNVERIFIED) */
#define YM3804_OFF_CTRL         0x00   /**< Control / reset register (tentative) */
#define YM3804_OFF_STATUS       0x01   /**< Status / busy flag (tentative) */
#define YM3804_OFF_DATA         0x02   /**< Data write port (tentative) */
#define YM3804_OFF_ADDR         0x03   /**< Address / register select (tentative) */


/* -------------------------------------------------------------------------
 * YM3807 – DSP Companion (present in EF1 and EF2)
 *
 * The YM3807 works alongside the YM3804.  Function and register map
 * are entirely undocumented.  Chip may implement a coefficient RAM
 * or a separate DSP sub-processor.
 * -------------------------------------------------------------------------- */
#define YM3807_EF1_BASE         DSP_EF1_REG(0x0000)  /**< YM3807 in EF1 — offset within block TBD */
#define YM3807_EF2_BASE         DSP_EF2_REG(0x0000)  /**< YM3807 in EF2 — offset within block TBD */

/* YM3807 candidate register offsets (UNVERIFIED) */
#define YM3807_OFF_CTRL         0x00   /**< Control register (tentative) */
#define YM3807_OFF_DATA         0x01   /**< Data port (tentative) */


/* -------------------------------------------------------------------------
 * YM6007 – EF1-only Chip
 *
 * Present only in the EF1 block.  Suspected function: reverb / chorus
 * engine or additional DSP routing.  No public documentation.
 * -------------------------------------------------------------------------- */
#define YM6007_EF1_BASE         DSP_EF1_REG(0x0000)  /**< YM6007 in EF1 — offset TBD */

/* YM6007 candidate register offsets (UNVERIFIED) */
#define YM6007_OFF_CTRL         0x00
#define YM6007_OFF_DATA         0x01


/* -------------------------------------------------------------------------
 * YM6104 – EF1-only Chip
 *
 * Present only in the EF1 block.  Suspected function: additional
 * effects processing or coefficient memory.  No public documentation.
 * -------------------------------------------------------------------------- */
#define YM6104_EF1_BASE         DSP_EF1_REG(0x0000)  /**< YM6104 in EF1 — offset TBD */

/* YM6104 candidate register offsets (UNVERIFIED) */
#define YM6104_OFF_CTRL         0x00
#define YM6104_OFF_DATA         0x01


/* =========================================================================
 * SECTION 3 – MEMORY
 *
 * Shared DRAM (IC35/IC36) at 0x400000 — CONFIRMED dual-purpose:
 *
 *   CPU side:  The ROM reset vector initialises the TMP68301 stack pointer
 *              just above 0x400000 (observed directly from firmware binary).
 *              This proves the CPU has read/write access to this region.
 *              The CPU uses the upper portion of this 64 KB window as its
 *              stack and working variable area.
 *
 *   DSP side:  The service manual block diagram shows IC35/36 feeding the
 *              DSP SECTION, specifically DSP2 instances 3, 4, and 5 (the
 *              main mix/master/send DSP units).  These units use the DRAM
 *              for audio delay lines and effects buffers.
 *
 *   Shared bus: A time-division or arbitrated bus allows both the TMP68301
 *              and the DSP to access the same physical DRAM.  This is a
 *              standard Yamaha DSP board design pattern.
 *
 * Probable memory layout within 0x400000–0x40FFFF:
 *   0x400000 – 0x40xxxx  DSP delay/effects buffer (lower region, DSP-written)
 *   0x40xxxx – 0x40FFFF  CPU stack and working variables (SP near top)
 *   Exact boundary TBD from firmware (watch for first CPU store instructions).
 *
 * IC93/IC94 (CPU section SRAM visible in block diagram):
 *   May be a separate static RAM at an unknown address used for patch/preset
 *   storage or display data — OR it may be the same ICs as IC35/36 seen
 *   from the CPU bus side.  Determine from PCB trace analysis or firmware.
 * ========================================================================= */

#define DMP9_SHARED_DRAM_BASE   0x400000UL  /**< Shared DRAM (IC35/36), 64 KB — CPU+DSP dual use */
#define DMP9_SHARED_DRAM_SIZE   0x010000UL  /**< DRAM size: 64 KB */
#define DMP9_SHARED_DRAM_END    (DMP9_SHARED_DRAM_BASE + DMP9_SHARED_DRAM_SIZE - 1)

/**
 * CPU stack top: SP is initialised just above 0x400000 at reset.
 * Actual value observed from ROM = 0x400000 + DRAM_SIZE = 0x410000, or
 * one of the values just below — read the exact SP init value from the
 * reset prologue (instruction at ROM+4 or first MOVE.L #imm, SP).
 */
#define DMP9_SP_INIT_REGION     DMP9_SHARED_DRAM_BASE  /**< SP initialised near top of this block */

/* Legacy aliases */
#define DMP9_DSP_DRAM_BASE      DMP9_SHARED_DRAM_BASE
#define DMP9_DSP_DRAM_SIZE      DMP9_SHARED_DRAM_SIZE
#define DMP9_DRAM_BASE          DMP9_SHARED_DRAM_BASE
#define DMP9_DRAM_SIZE          DMP9_SHARED_DRAM_SIZE


/* =========================================================================
 * SECTION 4 – FULL BOARD MEMORY MAP SUMMARY
 * ========================================================================= */

/**
 * @brief DMP9/DMP16 board memory map (absolute addresses)
 *
 * Status codes:
 *   [CONFIRMED] — address verified from firmware or service manual
 *   [TBD]       — address must be determined from firmware analysis
 */
typedef enum {
    DMP9_ROM_BASE       = 0x000000,   /**< [CONFIRMED] ROM — IC34, single firmware chip */
    DMP9_SHARED_DRAM    = 0x400000,   /**< [CONFIRMED] Shared DRAM IC35/36 (64 KB):
                                        *   CPU: stack+working RAM (SP set just above here at reset)
                                        *   DSP: delay/effects buffer for DSP2 units 3/4/5 */
    DMP9_DSP_EF1        = 0x460000,   /**< [CONFIRMED] DSP EF1: YM3804+YM6007+YM3807+YM6104 */
    DMP9_DSP_EF2        = 0x470000,   /**< [CONFIRMED] DSP EF2: YM3804+YM3807 */
    DMP9_LCD_CMD_ADDR   = 0x490000,   /**< [CONFIRMED] HD44780 command register (RS=0) */
    DMP9_LCD_DATA_ADDR  = 0x490001,   /**< [CONFIRMED] HD44780 data register (RS=1) */
    /* DMP9_CPU_SRAM  = ???  */        /**< [TBD] CPU working SRAM — IC93/94, address unknown */
    DMP9_TMP68301_REGS  = 0xFFFC00,   /**< [CONFIRMED] TMP68301 internal peripheral base */
} dmp9_memmap_t;


/* =========================================================================
 * SECTION 5 – DSP ARCHITECTURE NOTES
 *
 * Chip-to-function mapping (derived from service manual block diagrams
 * and signal names; must be verified by firmware analysis):
 *
 * DSP section signal formats (from diagram footnote legend):
 *   <ST-DSP>  — stereo DSP bus (SIO serial, connects CPU/ST-DSP block
 *               to DEQ2 and DSP2 units)
 *   <DSP2>    — secondary DSP bus (inter-chip SIO between DSP2 instances)
 *   <YAMAHA>  — Yamaha-proprietary format (used on IC21/22/23 connections)
 *
 * DEQ2 instances (IC26,27,28,37,38,39 — six units):
 *   Each handles one stereo input pair.  Receives SIO from CPU (<ST-DSP>)
 *   and passes processed data to a DSP2 instance.
 *   Tentative chip: YM3807 (DSP companion).
 *   SIO port signals per instance: SIO(in), SOO(out), SI1, SOI
 *
 * DSP2 instances (IC19,29,46,56,70,71 — five functional units + master):
 *   Each handles Mix/Level/On-Off for a channel group.
 *   Instance 5 (IC71) is the master: ST + Send Master.
 *   Receives <DSP2> from DEQ2 and <ST-DSP> from CPU.
 *   Has SRAM (IC66-68) for coefficient storage.
 *   Instances 3/4/5 also access the DRAM (IC35/36) for delay effects.
 *   Tentative chip: YM3804 (programmable DSP core).
 *   SIO port signals: SIO, SOO, SI1, SI2, SOI, SO2
 *
 * MEG (metering engine, IC22/23):
 *   Signals: AUXMEL0, AUXMEL1, OMEL0, OMEL1, IMEL0-3
 *   Connected via <YAMAHA> bus to the ST-DSP output stage (IC21).
 *   Probable function: per-channel peak/RMS level detection for
 *   front-panel meter LEDs (SIGNAL1-16 and CLIP signals).
 *   Tentative chip: YM6104 or YM6007.
 *
 * IC21 (<ST-DSP> final stage):
 *   Receives outputs from DSP2-5 (master) and MEG.
 *   Generates: ST1 OUT, SEND3/4, CLK(FOR MASTER), ST2 OUT, CLK(FOR ST2).
 *   Also connects to the output buffer IC14 and IC90 (SEL BUFFER).
 *   Probable chip: YM6007 (if not MEG) or another Yamaha serial DSP.
 *
 * MIDI (within CPU section):
 *   MIDI IN → IC24 (CPU); MIDI OUT and THRU generated by CPU.
 *   Likely routed through a UART (TMP68301 serial channel) or a
 *   dedicated MIDI UART chip.
 * ========================================================================= */


#ifdef __cplusplus
}
#endif

#endif /* DMP9_BOARD_REGS_H */
